# Generated by Django 2.2.12 on 2021-02-13 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='product id')),
                ('name', models.CharField(max_length=256, verbose_name='product name')),
                ('price', models.PositiveIntegerField(verbose_name='product price')),
                ('quantity', models.IntegerField(default=25000, verbose_name='product quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='purchase id')),
                ('quantity', models.IntegerField(verbose_name='purchase quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wholesale.Product')),
            ],
        ),
    ]
